### ISSUE TITLE
FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax

### ISSUE THREAD

**Issue by riccardoferrara** [py2exe/py2exe#57]
Hello,
I have developed a script that uses among others the package shapely, and I have created a .exe file of my main.py with py2exe. The issue is when I try to execute my main.exe file that results in this error:

FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

I precise that the shapely package works correctly when I launch main.py but it doesn't work when I execute main.exe, so I suppose that the "py version" finds the geos_c.dll without any issue.

I have tried to:

1) add shapely and or geos in my setup.py;
2) reinstall shapely with the wheel instead that pip;
3) add an env variable with the path of the file geos_c.dll;

here is my setup.py:

from distutils.core import setup
import py2exe

setup(
    windows=[{'script': 'main.py'}],
    options={
        'py2exe': 
        {
            'includes': ['lxml.etree', 'lxml._elementpath'],
        }
    }
)

Do you guys think that this issue could come from py2exe?

**Comment by albertosottile** [comment]
Hello, thanks for reporting this. Most likely, `py2exe` is failing to pack the DLLs included in the `shapely` wheels. 

Could you provide me a quick test code to check if `shapely` is imported correctly and can run from the packed executable? (a simplified version of your `main.py` script would be just fine)

**Comment by riccardoferrara** [comment]
Hello and thanks for your fast reply,
I can run any quick test yes off course but, just to be clear, the
executable does not execute at this moment, it gives me error and suggests
me to have a look in the log.
I would like to understand more what do you need, you mean a short code
where I use shapely for exemple?

Il giorno mar 1 dic 2020 alle ore 23:01 Alberto Sottile <
notifications@github.com> ha scritto:

**Comment by albertosottile** [comment]
I wrote an hook for `shapely` that should solve your issue. This hook will be included in the next release of py2exe, version 0.10.2.0, which should be published soon.

In the meantime, you can find prerelease wheels here: https://bintray.com/py2exe/py2exe/py2exe/0.10.2.0#files. If you could install one of these wheels and test if your issue is indeed solved, that would be great. Thanks for your feedback.

**Comment by albertosottile** [comment]
Fixed in [0.10.2.0](https://github.com/py2exe/py2exe/releases/tag/v0.10.2.0).

**Comment by ucb-pb** [comment]
Hey, I'm running py2exe version 0.10.2.1, and I'm still having this issue. Shapely version is 1.7.1.

**Comment by albertosottile** [comment]
I am unable to reproduce but, be advised that the import mechanism of `shapely` is quite brittle so, the packed executable works only if called from its library directory (essentially it looks for `geos_c.dll` only in `.`).  

Another suggestion that I can give you is to make sure that you have Visual C++ Redistributables installed in your test environment, as the error message in case those libraries are missing is exactly the same.

Finally, if you still would like assistance, I would encourage you to post here your test script and your setup script, so that I can reproduce your conditions.

**Comment by ucb-pb** [comment]
That works. Thank you.
